// src/shared/errors/error-codes.ts

export const ErrorCodes = {
  // Database errors
  DB_INIT_FAILED: 'E_DB_INIT_FAILED',
  DB_QUERY_FAILED: 'E_DB_QUERY_FAILED',
  DB_CONNECTION_LOST: 'E_DB_CONNECTION_LOST',
  DB_WRITE_FAILED: 'E_DB_WRITE_FAILED',
  DB_READ_FAILED: 'E_DB_READ_FAILED',
  DB_MIGRATION_FAILED: 'E_DB_MIGRATION_FAILED',
  DB_BACKUP_FAILED: 'E_DB_BACKUP_FAILED',
  DB_RESTORE_FAILED: 'E_DB_RESTORE_FAILED',

  // Serial port errors
  SERIAL_PORT_OPEN_FAILED: 'E_SERIAL_PORT_OPEN_FAILED',
  SERIAL_PORT_CLOSE_FAILED: 'E_SERIAL_PORT_CLOSE_FAILED',
  SERIAL_DISCONNECTED: 'E_SERIAL_DISCONNECTED',
  SERIAL_READ_FAILED: 'E_SERIAL_READ_FAILED',
  SERIAL_WRITE_FAILED: 'E_SERIAL_WRITE_FAILED',
  SERIAL_TIMEOUT: 'E_SERIAL_TIMEOUT',
  SERIAL_INVALID_DATA: 'E_SERIAL_INVALID_DATA',

  // Storage errors
  STORAGE_READ_FAILED: 'E_STORAGE_READ_FAILED',
  STORAGE_WRITE_FAILED: 'E_STORAGE_WRITE_FAILED',
  STORAGE_DELETE_FAILED: 'E_STORAGE_DELETE_FAILED',
  STORAGE_NOT_FOUND: 'E_STORAGE_NOT_FOUND',

  // Update errors
  UPDATE_CHECK_FAILED: 'E_UPDATE_CHECK_FAILED',
  UPDATE_DOWNLOAD_FAILED: 'E_UPDATE_DOWNLOAD_FAILED',
  UPDATE_INSTALL_FAILED: 'E_UPDATE_INSTALL_FAILED',

  // IPC errors
  IPC_TIMEOUT: 'E_IPC_TIMEOUT',
  IPC_INVALID_CHANNEL: 'E_IPC_INVALID_CHANNEL',
  IPC_HANDLER_ERROR: 'E_IPC_HANDLER_ERROR',

  // File system errors
  FS_READ_FAILED: 'E_FS_READ_FAILED',
  FS_WRITE_FAILED: 'E_FS_WRITE_FAILED',
  FS_DELETE_FAILED: 'E_FS_DELETE_FAILED',
  FS_NOT_FOUND: 'E_FS_NOT_FOUND',
  FS_PERMISSION_DENIED: 'E_FS_PERMISSION_DENIED',

  // Export/Import errors
  EXPORT_FAILED: 'E_EXPORT_FAILED',
  IMPORT_FAILED: 'E_IMPORT_FAILED',
  EXPORT_INVALID_FORMAT: 'E_EXPORT_INVALID_FORMAT',
  IMPORT_INVALID_DATA: 'E_IMPORT_INVALID_DATA',

  // Logger errors
  LOGGER_INIT_FAILED: 'E_LOGGER_INIT_FAILED',
  LOGGER_WRITE_FAILED: 'E_LOGGER_WRITE_FAILED',

  // Generic errors
  UNKNOWN: 'E_UNKNOWN',
  VALIDATION_FAILED: 'E_VALIDATION_FAILED',
  OPERATION_CANCELLED: 'E_OPERATION_CANCELLED',
  PERMISSION_DENIED: 'E_PERMISSION_DENIED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Маппинг префиксов кодов ошибок на области
 */
const ERROR_AREA_MAP: Record<string, string> = {
  E_DB: 'Database',
  E_SERIAL: 'Serial',
  E_STORAGE: 'Storage',
  E_UPDATE: 'Updater',
  E_IPC: 'IPC',
  E_FS: 'FileSystem',
  E_EXPORT: 'Export',
  E_IMPORT: 'Import',
  E_LOGGER: 'Logger',
};

/**
 * Получить область по коду ошибки
 */
export function getAreaFromErrorCode(code: string): string {
  // Извлекаем префикс (E_DB, E_SERIAL и т.д.)
  const match = code.match(/^(E_[A-Z]+)_/);

  if (match !== null) {
    const prefix = match[1];
    const area = ERROR_AREA_MAP[prefix];

    if (area !== undefined) {
      return area;
    }
  }

  return 'Unknown';
}
